language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install tox coverage docutils
  - pip install -r requirements.txt

script:
  - python setup.py check -m -r -s
  - python -m unittest
