language: python
python:
  - "3.3"
  - "3.6"
  - "nightly"

install:
  - pip install tox coverage docutils
  - pip install requirements.txt

script:
  - python setup.py check -m -r -s
  - python -m unittest